# Generated by Django 4.2.4 on 2023-10-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_enfermedad_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialclinico',
            old_name='usuario',
            new_name='user',
        ),
    ]
